# Generated by Django 4.1.1 on 2022-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0007_alter_bookmark_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='edit_url',
            field=models.CharField(auto_created=True, blank=True, max_length=255, null=True),
        ),
    ]
