# Generated by Django 4.1.1 on 2022-09-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_bookmark_edit_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='edit_url',
        ),
    ]
