# Generated by Django 4.1.1 on 2022-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0012_alter_bookmark_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
